import os

FLASK_APP=os.ENVIRON['FLASK_APP']
FLASK_ENV=os.ENVIRON['FLASK_ENV']
SECRET_KEY=os.ENVIRON['SECRET_KEY']
SQLITE3_DATABASE=os.ENVIRON['DATABASE']

# psql
DB_USERNAME=os.ENVIRON['DB_USERNAME']

